Padding & Anchor Overhaul.
novuscore/NovusCore-Client pull request #24
Opened 2020-11-16 11:59 UTC by TheGrimsey

**Changes:**
- Update how we handle positioning of elements to allow anchoring to parts of the screen and not just to parts of other elements.
- Add padding for elements.
- Clean up some includes.
- Add util function for converting from window coordinate space to ui coordinate space.
- Refactor some names.
- Add some missing functions to elements.
- Split off children & parent from Transform to Relation component.

**Tests Performed:**

- [X] Build
- [X] Tested in-game

**Targeted branch(es):**
- [x] Master

2020-12-09 11:31 UTC, Pursche requested changes
Looks good, mostly indentation issues.

2020-12-09 11:31 UTC, Pursche commented on client/UI/ECS/Systems/BuildSortKeySystem.cpp
> +            {
Indentation issue

2020-12-09 11:31 UTC, Pursche commented on client/UI/ECS/Systems/DeleteElementsSystem.cpp
> +        deleteView.each([&](entt::entity entityId) {
Curly brace on new line and double check indentation please

2020-12-09 11:31 UTC, Pursche commented on client/UI/ECS/Systems/UpdateBoundsSystem.cpp
> +            {
Fix indentation issue

2020-12-09 11:31 UTC, Pursche commented on client/UI/ECS/Systems/UpdateCullingSystem.cpp
> +            {
Fix indentation issue

2020-12-09 11:31 UTC, Pursche commented on client/UI/ECS/Systems/UpdateRenderingSystem.cpp
> +            {
Fix indentation please

2020-12-09 11:31 UTC, Pursche commented on client/UI/ECS/Systems/UpdateRenderingSystem.cpp
> +            {
Fix indentation please

2020-12-09 11:31 UTC, Pursche commented on client/UI/ECS/Systems/UpdateRenderingSystem.cpp
> +            {
Fix indentation please

2020-12-10 19:05 UTC, TheGrimsey commented
Should all be fixed now

2020-12-15 18:50 UTC, Pursche approved these changes

2020-12-15 18:52 UTC, merged